pollen_translate = {
    "Grass": "Трава",
    "Mold": "Плесень",
    "Ragweed": "Амброзия",
    "Tree": "Деревья",
    "UVIndex": "Ультрафиолет",
}

sticker = {
    "hi": "CAACAgIAAxkBAAIkRl4_O--_t6NteIjnwHkE54r3p2fcAAICEwAC2NjhAAGXOThJuBIDcRgE",
    "what": "CAACAgIAAxkBAAIkSF4_PLKZCqDLg5MQ0NtIAAGB0wdpIgACGBMAAtjY4QAB-3Tzhzbq_IkYBA",
    "start": "CAACAgIAAxkBAAIkSl4_PPLgCND-sRRtsvTjXc51bG_qAAIIEwAC2NjhAAFQoxJ3RFyVpxgE",
    "dog": "CAACAgIAAxkBAAIz9F5yGoTQi0pRfg_gJGb69CWdPJNQAAK6AQAC0lqIAaausk_orIbkGAQ",
}

forecast_icons = {
    "clear-day": "☀️",
    "clear-night": "🌕",
    "rain": "🌧",
    "snow": "❄️",
    "sleet": "❄️💦",
    "snow/rain": "❄️💦",
    "wind": "🌬",
    "fog": "🌫",
    "cloudy": "☁️",
    "partly-cloudy-day": "⛅️",
    "partly-cloudy-night": "🌚",
}

severity_icons = {0: "", 1: "‼️", 2: "❗️", 3: "❕", 4: "⚠️", 5: "ℹ️", 6: "", 7: ""}

accuweather_sticker = {
    0: "",
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: "",
    11: "",
    12: "",
    13: "",
    14: "",
    15: "",
    16: "",
    17: "",
    18: "",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "",
    25: "",
    26: "",
    27: "",
    28: "",
    29: "",
    30: "",
    31: "",
    32: "",
    33: "",
    34: "",
    35: "",
    36: "",
    37: "",
    38: "",
    39: "",
    40: "",
    41: "",
    42: "",
    43: "",
    44: "",
}

wind_direction_arrow = {
    "N": "⬇️",
    "NNE": "⬇️",
    "NE": "↙️",
    "ENE": "⬅️",
    "E": "⬅️",
    "ESE": "⬅️",
    "SE": "↖️",
    "SSE": "⬆️",
    "S": "⬆️",
    "SSW": "⬆️",
    "SW": "↗️",
    "WSW": "➡️",
    "W": "➡️",
    "WNW": "➡️",
    "NW": "↘️",
    "NNW": "⬇️",
}

words = {}
